### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by PreetishNiket** [PreetishNiket/NoteApp#3]

**Comment by sunkusaarthak** [comment]
hay hello can i add readme file

**Comment by sunkusaarthak** [comment]
Hi There!
Updated Readme File #8
please verify the pull request.

**Comment by PreetishNiket** [comment]
Merged a valid pull request

**Comment by sunkusaarthak** [comment]
hay can you please add "hacktoberfest-accepted"

**Comment by sunkusaarthak** [comment]
> hay can you please add "hacktoberfest-accepted" label to this pr

hay can you please do above request

**Comment by sunkusaarthak** [comment]
> > hay can you please add "hacktoberfest-accepted" label to this pr
> 
> hay can you please do above request

Hello Preetish Niket can you please add the above tag to this issue.

**Comment by sunkusaarthak** [comment]
Hello Preetish!
